all: mapping.png concept-extraction.png

concept-extraction.png: concept-extraction.dot
	dot -Tpng -o concept-extraction.png concept-extraction.dot

mapping.png: mapping.dot
	dot -Tpng -o mapping.png mapping.dot

# vim: set bg=dark:
